---
title: "Project"
author: "Yangmingqi (Simon) Guo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
market_origin <- read.csv("market_index_clean.csv")
first <- market_origin[1,]
market <- market_origin[2:3104,]
market$AAPL2 <- market_origin[,"AAPL"][1:3103]
market$Return <- (market$AAPL - market$AAPL2)/market$AAPL2
```

```{r}
library(lubridate)
market$Date <- market_origin$Date[2:3104]
date <- market$Date
first <- date[1]
day <- c()
for(i in 1:length(date)) {
  diff = round(difftime(date[i], first))
  day = c(day, diff)
}
market$Date <- day
fit <- lm(Return~., data = market)
summary(fit)
plot(fit)
```

##Backwark elimination:

```{r}
#drop EEM
summary(update(fit, .~.-EEM))
```

```{r}
#drop Date
summary(update(fit, .~.-Date-EEM))
```


```{r}
#drop Date
summary(update(fit, .~.-Date-EEM-BNDGLB))
```

```{r}
#drop Date
summary(update(fit, .~.-Date-EEM-BNDGLB-SPX))
```


##Based on the Backward method we choose model "Return ~ AAPL + VIX + SPGSCITR + AAPL2"

##Now we try using step

```{r}
nullmodel <- lm(Return~1, data=market)
fullmodel <- lm(Return~., data=market)
step(nullmodel, scope=list(upper=fullmodel), direction="both")
```

##Suprisingly it's the same one... Return ~ VIX + AAPL2 + AAPL + SPGSCITR

```{r}
test_model <- lm(Return ~ VIX + AAPL2 + AAPL + SPGSCITR, data = market)
plot(test_model)
summary(test_model)
plot(market$Return, residuals(test_model), xlab = "Return ratio", ylab = "Residuals")
abline(a = 0, b= 0, col = "red")
```

```{r}
poly_model <- lm(Return~ log(VIX) + log(AAPL2) + log(AAPL) + log(SPGSCITR), data = market)
plot(poly_model)
summary(poly_model)
plot(market$Return, residuals(poly_model), xlab = "Return ratio", ylab = "Residuals")
abline(a = 0, b= 0, col = "red")
```


```{r trying using subset selection}
library(leaps)
best.subset <- regsubsets(Return ~ ., data = market, nbest = 1)
#summary(best.subset)
tmp <- summary(best.subset)
tmp$adjr2
which.max(tmp$adjr2)
tmp$bic
which.min(tmp$bic)
#so this shows that either 3/4 variates should be included in the model [the difference is SPGSCITR]
```

```{r}
poly_model <- lm(Return~ log(VIX) + log(AAPL2) + log(AAPL), data = market)
plot(poly_model)
summary(poly_model)
plot(market$Return, residuals(poly_model), xlab = "Return ratio", ylab = "Residuals")
abline(a = 0, b= 0, col = "red")
```
```{r}
ts.plot(market$Return)
acf(market$Return)
acf(residuals(poly_model))
```

```{r fit model for AAPL}
AAPL_model <- lm(AAPL ~ SPX + VIX + SPGSCITR + BNDGLB + EEM + Date, data = market)
step(AAPL_model)
summary(AAPL_model)
```