---
title: "testing"
author: "Azoacha Forcheh, 20558994"
date: '2017-12-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
market_origin <- read.csv("market_index_clean.csv")
first <- market_origin[1,]
market <- market_origin[3:3104,]
market$AAPL2 <- market_origin[,"AAPL"][2:3103]
market$AAPL3 <- market_origin[,"AAPL"][1:3102]
market$Return <- (market$AAPL - market$AAPL2)/market$AAPL2
```

```{r}
library(lubridate)
market$Date <- market_origin$Date[3:3104]
date <- market$Date
first <- date[1]
day <- c()
for(i in 1:length(date)) {
  diff = round(difftime(date[i], first))
  day = c(day, diff)
}
market$Date <- day
```

```{r fig.width=10, fig.height=8}
fullmodel <- lm(Return~., data = market)
par(mfrow=c(2,2))
summary(fullmodel)
plot(fullmodel)
```

```{r}
# Helper function to avoid NA's when applying power 
#   to vector with negative values
exponent <- function(a, pow) (abs(a)^pow)*sign(a)
```

## Using 1/3 due to shape of residual-fitted plot
```{r fig.width=10, fig.height=8}
market.tr = market
market.tr$lReturn = exponent(market$Return, -1/3)
market.tr$lAAPL = exponent(market$AAPL, 3)
market.tr$lAAPL2 = exponent(market$AAPL2, 3)
market.tr$lAAPL3 = exponent(market$AAPL3, 3)

market.tr$Return = NULL
#market.tr$AAPL = NULL
#market.tr$AAPL2 = NULL

fullmodel2 = lm(lReturn~., data = market.tr)
par(mfrow=c(2,2))
plot(fullmodel2)
summary(fullmodel2)
```

