---
title: "Data Exploration"
author: "Azoacha Forcheh, 20558994"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Loading the data}
n = nrow(market_original)
market_original = read.csv('market_index_clean.csv')

first <- market_origin[1,]
market <- market_origin[2:3104,]
market$AAPL2 <- market_origin[,"AAPL"][1:3103]
market$Return <- (market$AAPL - market$AAPL2)/market$AAPL2
market$VIX2 = market_origin[,"VIX"][1:3103]
market$Return = market$Return/sqrt(market$VIX2)
```

```{r}
covars = c("AAPL","SPX","VIX","SPGSCITR","BNDGLB","EEM", "AAPL2", "VIX2")
```

```{r TS Plots, fig.height=10}
par(mfrow=c(4,2))
for (name in colnames(market)) {
  ts.plot(market[,name], 
          gpars=list(ylab=name,xlab='Day'))
}
```

Time series plot of the return seems to follow a separate pattern from the covariates.

```{r Autocorrelation Plots, fig.height=5, fig.width=7}
par(mfrow=c(4,2))
for (name in covars) {
  acf(market[,name], main=name, lag.max=10,
      xlab=paste0("Lag - ",name))
}
```

## All covariates have significant positive autocorrelation, while the return has no autocorrelation.

```{r fig.height=10, fig.width=7}
par(mfrow=c(4,2))
for (name in covars) {
  hist(market[,name]^(-1), xlab=name,
       main=paste("Histogram of ",name))
}
```


## AAPL, AAPL2 and VIX are positively skewed and may need transformation.

